Step_2.7.1

Возможно так же вместе с маской использовать срезы. И если нам нужно получить информцию только для Андрея и только за выходные, мы спокойно это делаем.

Что надо запомнить?

В скобках можно работать и с маской и с индексами одновременно!


In [1]:
import numpy as np

In [17]:
users = np.array(['Андрей', 'Михаил', 'Ольга', 'Джон', 'Андрей'])

In [18]:
visits = np.array([
    [1,0,1,0,0,1,0],
    [1,0,0,1,0,1,1],
    [1,0,1,0,1,1,1],
    [1,0,0,1,0,1,1],
    [1,0,1,0,1,1,1],
])

In [19]:
mask = users == 'Андрей'

In [20]:
visits[mask,5:]

array([[1, 0],
       [1, 1]])

Step_2.7.2

Допустим нам необходимо теперь выбрать всех пользователей, кроме Андрея и получить будние дни.

Мы с легкостью это делаем.

In [21]:
mask2 = users != 'Андрей'

In [22]:
visits[mask2,:5]

array([[1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 1, 0]])

В Numpy есть возможность инвертировать значения маски, чтобы не создавать дополнительные и т.д.

Делается это с помощью тильды. ~

In [23]:
visits[~mask,:5]

array([[1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 1, 0]])

Step_2.7.3

При работе с numpy для логических операций вы не работаете со стандартными питоновскими and и or. 

У numpy свои операторы:

Логическое ИЛИ:   |  (ищите выше клавиши Enter)

Логическое И:  & (ищите на клавише с цифрой 7)  

Нам необходимо вытянуть теперь двух пользователей, Михаил и Джон

В данном случае мы делаем двойную маску. И используем в Numpy OR == |

In [26]:
mask_MJ = (users == 'Михаил') | (users == 'Джон')

In [27]:
visits[mask_MJ]

array([[1, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0, 1, 1]])

In [29]:
#Инверсия маски
visits[~mask_MJ]

array([[1, 0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1]])

Step_2.7.4

Что надо взять на заметку:

Раньше мы умели вытягивать значения вот так:

m2d[1, : ]  <- передаем конкретный индекс (один)

m2d[1:4, : ]  <- передаем слайсинг (диапазон индексов)

m2d[[True, True, False, True], : ]  <- передаем маску



*А теперь знаем еще про один способ - прихотливая индексация:*

m2d[[0, 2, 4], : ]  - передаем список/массив с индексами по которым надо вытащить значения. 

Индексы могут идти не по порядку.

In [33]:
m2d = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4],[5,5,5,5]])
m2d

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5]])

In [34]:
m2d[[0,2,4]]

array([[1, 1, 1, 1],
       [3, 3, 3, 3],
       [5, 5, 5, 5]])

In [35]:
m2d[[4,2,0]]

array([[5, 5, 5, 5],
       [3, 3, 3, 3],
       [1, 1, 1, 1]])

Step_2.7.6

Интересно заметить, что в случае записи

m2d[[4,2,0],[1,2,3]]

Будет совершенно не то, что мы ожидали. Мы хотели вытянуть столбцы, но увы-с.

В целом это может быть полезно в других случаях.

Numpy воспринимет это так, как если нам нужны элементы, расположенные по конкретным индексам. Парам индексов. То есть 4,1; 2,1; 0,3

In [36]:
m2d[[4,2,0],[1,2,3]]

array([5, 3, 1])

И все так получить нужные нам колонки в Numpy можно следующим методом:

In [40]:
#Способ 1
m2d[[0, 2, 4]][:,[1,2,3]]

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5]])

In [37]:
#Способ 2:
m2d[[0, 2, 4], 1: ]

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5]])

Step_2.7.8 - Трансформации, .reshape

!Важно. При передаче количества строк и столбцов в функцию .reshape(). Умножая одно значение на другое, мы должны получать количество элементов! В противном случае, мы будем получать ошибку.

In [42]:
m1 = np.arange(50)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [44]:
#Предположим, я хочу вывести данный одномерный массив в матрицу 5 строк, 10 столбцов
m1.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
#имитация ошибки
m1.reshape(4,10)

ValueError: cannot reshape array of size 50 into shape (4,10)

Step_2.7.10 - Создание трехмерного массива.

!Здесь тоже важно, чтобы при перемножение количество элементов совпадало!.

In [47]:
m1.reshape(5,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [49]:
#Имитация ошибки
m1.reshape(2,2,5)

ValueError: cannot reshape array of size 50 into shape (2,2,5)

Step_2.7.10 - Задача
На вход функции подается двумерный массив:

![Картинка испарилась(((](https://ucarecdn.com/49ccd304-d7b8-4203-9457-1cf4338b4056/)

доработайте функцию так чтобы она вернула маску по которой потом можно будет выбрать значения меньше 20 или больше 40.

In [ ]:
import numpy as np

def solution(arr):
    arr = (arr < 20) | (arr > 40)
    return arr

Step_2.7.11 - Задача
На вход функции подается двумерный массив:

![Картинка испарилась(((](https://ucarecdn.com/62de17b8-9f2b-41e1-964e-736642e80acc/)

доработайте функцию так чтобы она вернула значения, которые лежат на главной диагонали. Значения должны быть в одномерном массиве (Для особых знатоков: функцией diag не пользоваться!). Работайте с прихотливой индексацией.

In [61]:
#мое решение
import numpy as np

def solution(arr):
    arr = arr[[0,1,2,3,4],[0,1,2,3,4]]
    return arr

In [71]:
test = np.arange(25)
test = test.reshape(5,5)

In [72]:
solution(test)

array([ 0,  6, 12, 18, 24])

In [73]:
#пара вариантов других возможных решений
import numpy as np

def solution(arr):
    indx = np.arange(len(arr))
    return arr[indx, indx]

In [ ]:
import numpy as np

def solution(arr):
    arr = arr[[range(5)], [range(5)]]#ваш код здесь
    return arr

Step_2.7.13 - Задача
На вход функции подается двумерный массив:

![Картинка испарилась(((](https://ucarecdn.com/3bb5b4e9-f8bf-4230-be95-304d24c5ae1f/)

доработайте функцию так чтобы она вернула значения, которые лежат на побочной диагонали. Значения должны быть в одномерном массиве array([1, 32, 84, 19, 20]) (Для особых знатоков: функцией diag не пользоваться!). Работайте с прихотливой индексацией.

In [85]:
import numpy as np

def solution(arr):
    arr = arr[[4,3,2,1,0],[0,1,2,3,4]]
    return arr

In [86]:
solution(test)

array([20, 16, 12,  8,  4])

In [84]:
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
matrix = np.array([[10,12,14,18,20],[8,22,18,19,12],[4,14,84,38,11],[2,32,4,31,9],[1,11,1,8,6]])
matrix

array([[10, 12, 14, 18, 20],
       [ 8, 22, 18, 19, 12],
       [ 4, 14, 84, 38, 11],
       [ 2, 32,  4, 31,  9],
       [ 1, 11,  1,  8,  6]])

Step 2.8.2 - На вход подается одномерный массив, преобразуйте его в матрицу с 5 строками и 6 столбцами

In [8]:
import numpy as np
def solution(arr):
    arr = arr.reshape(5,6)
    return arr

Step 2.8.3 - На вход подается одномерный массив, преобразуйте его в трехмерный массив, где каждая матрица будет размером 4х5 и таких матриц должно быть 10

In [ ]:
import numpy as np
def solution(arr):
    return arr.reshape(10,4,5)

Step 2.8.5 - На вход подается двумерная матрица
![Картинка испарилась(((](https://ucarecdn.com/6b649a66-c9ba-4949-851e-8e87820df813/)
вытяните из нее последние три строки, но так чтобы строки были расположены в обратном порядке:
![Картинка испарилась(((](https://ucarecdn.com/6bcec988-10bc-4c44-ac3c-8c4ef5500c4a/)

In [10]:
# 1
import numpy as np
def solution(arr):
    return arr[[4,3,2]]

In [11]:
solution(matrix)

array([[ 1, 11,  1,  8,  6],
       [ 2, 32,  4, 31,  9],
       [ 4, 14, 84, 38, 11]])

In [ ]:
# 2
import numpy as np
def solution(arr):
    return arr[[~x for x in range(3)]]

Step 2.8.6 - На вход подается двумерная матрица
![Картинка испарилась(((](https://ucarecdn.com/6b649a66-c9ba-4949-851e-8e87820df813/)
вытяните из нее последние три строки, но так чтобы строки были расположены в обратном порядке. 
Затем возьмите только последние два столбца:
![Картинка испарилась(((](https://ucarecdn.com/24a15cb1-a2be-4ef2-b551-bab7c8a1854f/)

In [12]:
import numpy as np
def solution(arr):
    return arr[[4,3,2],3:]

In [13]:
solution(matrix)

array([[ 8,  6],
       [31,  9],
       [38, 11]])

Step 2.8.6 - На вход подается двумерная матрица размером 5х5. Преобразуйте ее в одномерный массив.

In [ ]:
import numpy as np
def solution(arr):
    return arr.reshape(25)

Step 2.8.6 - На вход подается трехмерная матрица размером 6х5х5. Преобразуйте ее в одномерный массив.

In [ ]:
#1
import numpy as np

def solution(arr):
    return arr.reshape(6*5*5)

In [ ]:
#2
import numpy as np

def solution(arr):
    arr = arr.reshape(-1)
    return arr

In [ ]:
#3
import numpy as np

def solution(arr):
    arr1 = arr.flatten()
    return arr1

In [ ]:
#4
import numpy as np

def solution(arr):
    arr.shape = -1
    return arr