## Step_2.1.1
ссылка на официальную документацию numpy: https://numpy.org/doc/stable/
Предположим, что нам необходимо создавать таблицу стандартными методами python. Как мы это реализуем.

In [3]:
#Реализую таблицу первым способом, с помощью обычного списка.
table1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [4]:
#получим значение 5. Вот так бы мы работали с таблицами, если бы у нас не было pandas.
table1[1][1]

5

In [5]:
#Реализуем таблицу с помощью словаря.
table2 = {'Столбец1' : [1,4,7],
         'Столбец2' : [2,5,6],
         'Столбец3' : [7,8,9],
         }

In [8]:
#снова получим 5.Сначала обратимся по ключу, а потом по индексу элемента.
table2['Столбец2'][1]

5

In [ ]:
#Идея заключается в том, что для хранения данных необходимо иметь какой то контейнер. 
#Будет это список или словарь
#Numpy - предоставляет контейнеры для хранения данных.
#Именно эту библиотеку за основу взяли разработчики Pandas

## Step_2.1.2 Библиотека Numpy
В данной части посмотрим на скорость выполнения задачи стандартными инструментами python. И на то, как быстро с этим справится библиотека Numpy.

In [9]:
#импортируем библиотеку Numpy
import numpy as np

In [17]:
#создаем список на 1кк элементов
lst = list(range(1_000_000))

In [19]:
len(lst)

1000000

In [20]:
#создаем аналогичный массив с помощью библиотеки numpy
arr = np.arange(1_000_000)

In [21]:
len(arr)

1000000

In [22]:
#возведем каждый элемент в квадрат 10 раз и подсчитаем время выполнения данной операции, командой %time
%time for _ in range(10): lst2 = [x**2 for x in lst]
#результат: 2,62с

CPU times: total: 2.62 s
Wall time: 2.62 s


In [23]:
#возведем каждый элемент в квадрат 10 раз с помощью numpy, командой %time
%time for _ in range(10): arr2 = arr ** 2
#результат: 20 мс. Выполнение в сотни раз быстрее

CPU times: total: 46.9 ms
Wall time: 20 ms


In [ ]:
#т.к. у нас будет огромное количество данных. А так же многие другие библиотеки основаны на numpy.
#Изучая его сейчас я убиваю сразу двух зайцев.

## Step_2.1.3 Установка Numpy

In [ ]:
#т.к. я работаю через jupyterNotebook, у меня numpy установлен по умолчанию
#Для установки можно использовать !pip install numpy, так же можно делать это специальным средствами
#различных IDE не вводя никакие команды. Например в PyCharm

In [24]:
# Так же можно посмотреть есть ли эта библиотека у нас с помощью следующей команды
!pip show numpy

Name: numpy
Version: 1.21.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\user\anaconda3\lib\site-packages
Requires: 
Required-by: xarray, tifffile, tables, statsmodels, seaborn, scipy, scikit-learn, scikit-image, PyWavelets, pyerfa, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, imagecodecs, hvplot, holoviews, h5py, gensim, datashape, datashader, daal4py, Bottleneck, bokeh, bkcharts, astropy


In [ ]:
#При выполнении команды так же видно, какие библиотеки используют numpy

## Step_2.1.4 Работа с numpy
Каждый раз работу с библиотекой начинаем с ее Импорта

In [25]:
import numpy as np

In [33]:
#Создание обычного массива
arr1 = np.array([1,2,3,4.5])
arr1

array([1. , 2. , 3. , 4.5])

In [34]:
#Создание вложенного массива
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
#измерение длины нашего массива
len(arr1)


2

In [37]:
#в данном случае, мы полчим поличество вложенных списков
len(arr2)

2

In [38]:
#для того, чтобы понять какое у нас количество массивов и количество элементов в 
#подмассивах применим .shape
arr2.shape

(2, 3)

In [39]:
#мне вот интересно, а если у нас будет не одинаковое количество
arr3 = np.array([[1,2,3],[4,5,6,7]])
arr3.shape
#забавно в данном случае эта функция нам не поможет в курсе ничего про это нет=(

C:\Users\user\AppData\Local\Temp\ipykernel_18360\2919537873.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3 = np.array([[1,2,3],[4,5,6,7]])


(2,)

In [44]:
#я поискал еще возможные варианты функция для подсчета количества элементво массива. 
#Все они так же работают
np.size(arr2) 

6

In [45]:
np.size(arr3)

2

In [46]:
np.prod(arr2.shape)

6

In [47]:
np.prod(arr3.shape)

2

Свойство ndim - сокращение от number of dimensions (переводится как количество измерений).  Поможет ответить на вопрос: а сколько измерений в моем массиве (какая вложенность)? Наиболее частые случаи:
Если ndim =1 значит у вас 1D array (см. выше). Он же одномерный массив.
Если ndim =2 значит у вас 2D array (см. выше). Он же двумерный массив. Она же матрица.
Если ndim =3 значит у вас 3D array (см. выше). 
2) Свойство shape (переводится как форма) - показывает размер каждого измерений.
Если у вас shape = (4,) это значит, что у вас одномерный массив длинной 4
Если у вас shape = (2, 3) это значит, что у вас двумерный массив (массив, который состоит из подмассивов). Каждый подмассив длинной 3.
Если у вас shape = (4, 3, 2) это значит, что у вас трехмерный массив. Но из чего он состоит? Представьте себе двумерный массив размером (3, 2). Вот таких двухмерных массивов (называют матрицами) у вас будет 4.

Про shape мы еще будем говорить. Если не совсем уловили, ничего страшного) 

In [48]:
arr2.ndim

2

In [49]:
arr3.ndim

1

## Step_2.1.6 Типы данных
1) Когда вы создаете массив, Numpy пытается понять из каких элементов вы пытаетесь его создать и подбирает наиболее подходящий тип данных.
Зачем Numpy вообще что-то подбирать? - Это долгая история, просто запомните, что у каждого элемента массива есть свой тип данных. Это сильно помогает массиву быть быстрее чем его брату питоновскому списку. Numpy старается не выдавать ошибку.
2) Свойство dtype подскажет, какой тип данных у каждого элемента вашего массива. 

In [50]:
#нампаевским массивам присваивается тип. Посмотреть его можно через .dtype
arr1.dtype

dtype('float64')

In [51]:
arr2.dtype

dtype('int32')

## Step_2.1.7 Функция .zeros

In [ ]:
lst = [0, 0, 0, 0, 0, 0, 0]

In [54]:
#Используем функцию zeros
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [55]:
#создаем вложенные массивы 
#arr2 = np.zeros((a, b))
#где а - количество подмассивов, b - количество элементов в подмассивах
arr2 = np.zeros((2, 3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

## Step_2.1.8 Инициализация значений элементов .ones

In [57]:
arr1 = np.ones(5)
arr1

array([1., 1., 1., 1., 1.])

In [56]:
arr2 = np.ones((2, 3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

## Step_2.1.9 функция .full

In [ ]:
#Функция .full может заполняться теми значениями, которые нам нужны
#правда они все так же однотивны
arr1 = np.full(5, -1)
arr1

In [58]:
arr2 = np.full((2,3), -1)
arr2

array([[-1, -1, -1],
       [-1, -1, -1]])

## Step_2.1.10 np.arange создание массивов

In [59]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Step_2.1.12
Напишите функцию, которая возвращает numpy массив на основе предложенного списка (lst).

In [63]:
import numpy as np

def solution(lst):
    arr = np.array(lst)
    return arr

## Step_2.1.12
Напишите функцию, которая возвращает одномерный массив длинной 100 и заполненный нулями.

In [ ]:
import numpy as np

def solution():
    arr = np.zeros(100)
    return arr

In [ ]:
#Step_2.2.3 - Создайте массив заполненный нулями у которого shape = (2, 5)
import numpy as np

def solution():
    arr = np.zeros((2,5))
    return arr

In [ ]:
#Step_2.2.5 - Создайте массив заполненный единицами, 
#у которого 5 строк и 8 столбцов (5 вложенных массивов длинной 8)
import numpy as np

def solution():
    arr = np.ones((5,8))
    return arr

In [ ]:
#Step_2.2.5 - Создайте двумерный массив размером 5 х 2, который полностью будет заполнен значением 'G' 
import numpy as np

def solution():
    arr = np.full((5, 2), 'G')
    return arr