### STEP_2.3.1
Типы данных - https://www.javatpoint.com/numpy-datatypes
Иногда необходимо, самим выбирать, какой тип данных будет в массиве.

In [2]:
#укажем тип данных с плавающей точкой
import numpy as np
arr1 = np.array([1,2,3,4,5], dtype=np.float64)
arr1.dtype

dtype('float64')

In [5]:
#допустим, нам необходимо изменить тип данных, используем функцию .astype
arr_int = arr1.astype(np.int64)
arr_int

array([1, 2, 3, 4, 5], dtype=int64)

### STEP_2.3.2-2.3.3_Конвертация данных из Int64 во float и обратно

In [6]:
#создаем массив с дробной частью
arr1 = np.array([1.5,2.5,3.5,4.5,5.5], dtype=np.float64)

In [8]:
arr1.dtype

dtype('float64')

In [9]:
#предположим, что нам необходимо снова сделать INT
#что же произойдет? Numpy или отрежет дробную часть или попробует округлить наши числа
arr2 = arr1.astype(np.int64)
arr2
#Десятичная часть будет отрезана. Останется только целая часть
#ОБЯЗАТЕЛЬНО НАДО ЗАПОМНИТЬ ЭТО ПРИ РАБОТЕ С ДАННЫМИ!

array([1, 2, 3, 4, 5], dtype=int64)

### STEP_2.3.5 Данные с типом Str

In [11]:
arr1 = np.array(['1.5', '2', '3.5', 4, 6])
arr1

array(['1.5', '2', '3.5', '4', '6'], dtype='<U11')

In [13]:
arr2 = arr1.astype(np.float64)
arr2

array([1.5, 2. , 3.5, 4. , 6. ])

In [14]:
arr2.dtype

dtype('float64')

In [17]:
#допустим человек, который заполняд данные совершил ошибку, не один раз
arr1 = np.array(['1.5', '2', '3!5', 4, 6])

In [18]:
#пыатемся преобразовать к float
#такое бывает, не стоит этого бояться. Как это исправить будем смотреть дальше
arr2 = arr1.astype(np.float64)

ValueError: could not convert string to float: '3!5'

### STEP_2.3.6 Данные с типом Str

In [21]:
m1 = np.arange(10)
m1.dtype

dtype('int32')

In [22]:
m2 = np.array([1.1, 2.2, 3.3], dtype=np.float64)
m2.dtype

dtype('float64')

In [23]:
#Первый вариант приведения к Int
m1.astype(np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
#или мы можем обратиться ко второму массиву, с другим типо
m11 = m1.astype(m2.dtype)
m11.dtype

dtype('float64')

In [27]:
m1.dtype

dtype('int32')

In [28]:
#Основная суть в том, что у numpy массивов есть типы данных

### STEP_2.3.7 Арифметические операции с массивами

In [30]:
lst = [1,2,3,4]

In [31]:
#попробуем перемножить. Результат: просто повторяется изначальный массив
lst * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [32]:
#массивы numpy работают иначе
m1 = np.array(lst)
m1

array([1, 2, 3, 4])

In [34]:
#каждый элемент массива numpy перемножился
#таким образом мы не зацикливаемся на циклы for
m1 * 2

array([2, 4, 6, 8])

In [35]:
m1 * m1

array([ 1,  4,  9, 16])

In [36]:
#сложение
lst + 1

TypeError: can only concatenate list (not "int") to list

In [37]:
m1 + 1

array([2, 3, 4, 5])

In [38]:
lst ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [39]:
m1 **2 

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
#Проверим эти функции для многомерных списков

In [41]:
m2d = np.array([[1,2,3],[4,5,6]])
m2d

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
#убедимся в том, что все прекрасно работает
m2d ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [43]:
m2d + 2.4

array([[3.4, 4.4, 5.4],
       [6.4, 7.4, 8.4]])

### STEP_2.3.8 Сравнение массивов со списками

In [44]:
#Сравним данные температуры за 2 дня
temp10_01_2023 = [10.5, 5.5, 8.5] 

In [45]:
temp11_01_2023 = [11.5, 2.5, 3.5] 

In [46]:
#Получаем булевое значение
temp10_01_2023 > temp11_01_2023

False

In [47]:
#Проделаем тоже самое с массивами numpy
t1 = np.array(temp10_01_2023)

In [48]:
t2 = np.array(temp11_01_2023)

In [49]:
#здесь мы получаем уже набор буевых значений. Каждое значение сравнивалось с каждым
t1 > t2

array([False,  True,  True])

In [50]:
m3 = t1 > t2
m3

array([False,  True,  True])

### STEP_2.3.10 Срезы

In [52]:
z1 = np.arange(10)
z1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
z1[4]

4

In [55]:
z1[4] = 0
z1

array([0, 1, 2, 3, 0, 5, 6, 7, 8, 9])

In [56]:
z1[4:7]

array([0, 5, 6])

### STEP_2.3.10 Слайсинг

In [57]:
#создаем новый массив на основе первого
z2 = z1[4:7]
z2

array([0, 5, 6])

In [58]:
#изменим в нем одно из значений
z2[0] = 387
z2

array([387,   5,   6])

In [59]:
#Обнаружим то, что в первоначальном массиве данное значение так же было изменено!
#Очень важно помнить об этом, когда мы работаем с массивами данных!!!
z1

array([  0,   1,   2,   3, 387,   5,   6,   7,   8,   9])

In [ ]:
#STEP_2.3.13_Задача
#Напишите функцию, которая на основе существующего списка создает numpy массив с типом float64
import numpy as np

def solution(lst):
    arr = np.array(lst, dtype=np.float64)
    return arr

In [ ]:
#STEP_2.3.15_Задача
#К вам в распоряжение поступает массив arr с типом float64. 
#Преобразуйте, пожалуйста, в int32
import numpy as np

def solution(lst):
    arr = lst.astype(np.int32)
    return arr