In [2]:
import numpy as np

In [3]:
m1 = np.array([1,2,3,4])

In [4]:
m2 = np.array([0,3,1,6])

In [5]:
np.maximum(m1, m2)

array([1, 3, 3, 6])

In [6]:
#для получения маски булевых значений при сравнении двух массивов есть функция:
np.greater(m1,m2)
#она эквивалентна m1 > m2

array([ True, False,  True, False])

In [7]:
#мы можем получить маску
mask_g = np.greater(m1,m2)

In [8]:
#Получим из m1 значения по маске
m1[mask_g]

array([1, 3])

In [ ]:
#Чтобы сравнить больше или равно >= записывается следующая ф-я:

In [17]:
m1 = np.array([1,2,3,4])

In [18]:
m2 = np.array([0,3,3,6])

In [19]:
np.greater_equal(m1,m2)

array([ True, False,  True, False])

In [20]:
m1 >= m2

array([ True, False,  True, False])

In [21]:
m1 > m2

array([ True, False, False, False])

In [22]:
#Для проверки m1 < m2 применяется ф-я less:
m2 < m1

array([ True, False, False, False])

In [23]:
np.less(m1, m2)

array([False,  True, False,  True])

In [ ]:
# <= соответственно less_equal

In [24]:
np.less_equal(m1, m2)

array([False,  True,  True,  True])

In [25]:
#Здесь важно поставить двойное равенство. Если будет =, то мы просто приравняем матрицы
m1 == m2

array([False, False,  True, False])

In [39]:
m1 = np.array([1,2,3,4])

In [40]:
m2 = np.array([0,-3,3,-6])

In [36]:
#функции можно комбинировать. Вкладывать друг в друга
np.abs(np.minimum(m1, m2))

array([0, 3, 3, 6])

In [41]:
np.sqrt(m1 ** 2 + m2 ** 3)

C:\Users\user\AppData\Local\Temp\ipykernel_17920\3313742552.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(m1 ** 2 + m2 ** 3)


array([ 1., nan,  6., nan])

### Where
Стандартный IF. np.where(условие, что сделать если выполняется, что сделать если не выполняется)
example:

np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
#Если значение <0 , то выводит 100, если > 0, то выводит -100

In [43]:
m1 = np.array([2, -3, 4, -6, 7, -8])
m1

array([ 2, -3,  4, -6,  7, -8])

In [44]:
np.where(m1 > 0,100, -100)

array([ 100, -100,  100, -100,  100, -100])

Проверим как это работает для двумерных массивов

In [45]:
m2d = np.arange(30).reshape(5,6)
m2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [46]:
np.where(m2d < 10, 0, m2d)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### Математические и статические функции


In [47]:
m1 = np.arange(6)
m1

array([0, 1, 2, 3, 4, 5])

In [48]:
#суммируем значения
np.sum(m1)

15

In [50]:
#аналогичный способ записи
m1.sum()

15

In [49]:
#Получаем среднее
np.mean(m1)

2.5

In [51]:
m1.mean()

2.5

In [55]:
#теперь посмотрим на двумерные массивы
m2d = np.arange(12).reshape((2,6))
m2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
Axis - дает возможность нам считать по столбцам(Axis = 0) или строкам(Axis = 1)

In [56]:
m2d.sum(axis = 0)

array([ 6,  8, 10, 12, 14, 16])

In [57]:
m2d.sum(axis = 1)

array([15, 51])

In [58]:
#Ф-я минимального значения 
m2d.min()

0

In [59]:
#Ф-я максимального значения
m2d.max()

11

### Функции стандартного отклонения .std(), .var()

In [60]:
m2d.std() # standart deviation

3.452052529534663

In [61]:
m2d.var()

11.916666666666666

### Функции .argmin(), argmax()
Получение индексов минимального и максимального значений

In [62]:
m1 = np.array([1,0,5,6,2]) 

In [63]:
m1.argmin() #индекс минимального значения

1

In [64]:
m1.argmax() #индекс максимального значения

3

### Суммирование булевых значений
True = 1, False = 0

In [70]:
bools_arr = np.array([True, True, False, True])

In [71]:
num_arr = np.array([1,1,0,1])

In [72]:
bools_arr.sum()

3

In [73]:
num_arr.sum()

3

Step_2.11.11 - На вход подаётся два одномерных массива. Сравните их поэлементно: постройте новый массив из минимальных значений. У нового одномерного массива найдите максимальное значение

In [ ]:
import numpy as np

def solution(m1, m2):
    arr_min = np.minimum(m1, m2)
    result = np.max(arr_min)
    return result

Step_2.11.13 - На вход подаётся два одномерных массива. Сравните их поэлементно. Постройте новый массив из максимальных значений. У нового одномерного массива найдите минимальное значение

In [75]:
import numpy as np

def solution(m1, m2):
    arr_max = np.maximum(m1, m2)
    result = np.min(arr_max)
    return result

Step_2.11.15 - На вход подаётся одномерный массив. Найдите среднее значение.

In [ ]:
import numpy as np

def solution(m1):
    result = np.mean(m1)
    return result