In [9]:
import numpy as np

#### Функции .any() и .all()
.any() - выведет True, если есть хотя бы 1 True
.all() - выведет True, если все элементы True

In [10]:
bools_arr_1 = np.array([True,True,False,True])

In [11]:
bools_arr_2 = np.array([False,False,False,False])

In [12]:
bools_arr_3 = np.array([True,True,True,True])

In [13]:
bools_arr_1.any()

True

In [14]:
bools_arr_2.any()

False

In [15]:
bools_arr_3.any()

True

In [16]:
bools_arr_1.all()

False

In [18]:
bools_arr_2.any()

False

In [19]:
bools_arr_3.any()

True

### Функция .sort()
Данная функция ничего не возвращает. Она сортирует уже созданный массив.

In [21]:
m1 = np.array([-1,6,2,3,0,-23])

In [22]:
m1.sort()

In [23]:
m1

array([-23,  -1,   0,   2,   3,   6])

Сортировка двумерной матрицы

In [32]:
m2d = np.array([[1,5,0,-2],[6,2,0,-8],[-2,4,8,12]])
m2d

array([[ 1,  5,  0, -2],
       [ 6,  2,  0, -8],
       [-2,  4,  8, 12]])

In [31]:
#Сортирует по столбцам
m2d.sort(axis=0)
m2d

array([[-2,  2,  0, -8],
       [ 1,  4,  0, -2],
       [ 6,  5,  8, 12]])

In [34]:
#Сортирует по строкам
m2d.sort(axis=1) 
m2d

array([[-2,  0,  1,  5],
       [-8,  0,  2,  6],
       [-2,  4,  8, 12]])

### Дубликаты, ф-я np.unique()
Проверим наш массив на наличие дубликатов

In [36]:
names = np.array(['Ivan','Andrey','Roman','Andrey','Sergey','Ivan'])
names

array(['Ivan', 'Andrey', 'Roman', 'Andrey', 'Sergey', 'Ivan'], dtype='<U6')

In [39]:
unames = np.unique(names)

In [40]:
len(unames)

4

In [42]:
#Проверка на наличие дубликатов
len(unames) == len(names)

False

#### Функция np.in1d()
Проверим наличие определенных значений(которые могут нас интересовать) в нашем массиве

In [44]:
names = np.array(['Ivan','Andrey','Roman','Andrey','Sergey','Ivan'])
names

array(['Ivan', 'Andrey', 'Roman', 'Andrey', 'Sergey', 'Ivan'], dtype='<U6')

In [45]:
names == 'Roman'

array([False, False,  True, False, False, False])

Допустим интересующих нас значений несколько

In [46]:
(names == 'Roman') | (names == 'Andrey')

array([False,  True,  True,  True, False, False])

In [48]:
#Ну мы же не можем делать так до бесконечности, применим функцию
#Допустим нам надо проверить пользователей. В BlackList
np.in1d(names, ['Roman', 'Andrey'])

array([False,  True,  True,  True, False, False])

#### Линейная Алгебра

In [49]:
m = np.array([[1,5,0],[6,2,0],[-2,4,8]])
m

array([[ 1,  5,  0],
       [ 6,  2,  0],
       [-2,  4,  8]])

In [50]:
m.T

array([[ 1,  6, -2],
       [ 5,  2,  4],
       [ 0,  0,  8]])

In [51]:
#Функция np.dot - перемножает матрицы
#перемножим транспонированную матрицу на ее саму
np.dot(m.T, m)

array([[ 41,   9, -16],
       [  9,  45,  32],
       [-16,  32,  64]])

Детерминант матрицы - Определи́тель (детермина́нт) в линейной алгебре — скалярная величина, которая характеризует ориентированное «растяжение» или «сжатие» многомерного евклидова пространства после преобразования матрицей; имеет смысл только для квадратных матриц.
Определитель матрицы равен произведению её собственных значений.
Если квадратная матрица выражает линейное преобразование, то её определитель не меняется при замене базиса линейного пространства.

In [52]:
np.linalg.det(m)

-224.00000000000014

In [53]:
#Обратная матрица
np.linalg.inv(m)

array([[-0.07142857,  0.17857143,  0.        ],
       [ 0.21428571, -0.03571429,  0.        ],
       [-0.125     ,  0.0625    ,  0.125     ]])

In [54]:
#Получение главной диагонали матрицы
m

array([[ 1,  5,  0],
       [ 6,  2,  0],
       [-2,  4,  8]])

In [55]:
np.diag(m)

array([1, 2, 8])

In [63]:
#Получение элементов выше главной диагонали
#Делается это с помощью специального параметра k
np.diag(m, k=1)

array([5, 0])

In [56]:
#Получим верхний треугольник матрицы
np.triu(m)

array([[1, 5, 0],
       [0, 2, 0],
       [0, 0, 8]])

In [58]:
#Получим сумму верхнего треугольника
np.triu(m).sum()

16

In [57]:
#Получим нижний треугольник матрицы
np.tril(m)

array([[ 1,  0,  0],
       [ 6,  2,  0],
       [-2,  4,  8]])

In [59]:
#Получим сумму нижнего треугольника
np.tril(m).sum()

19

In [60]:
#сумма элементов главной и побочной диагоналей
np.trace(m)

11

### Модуль RANDOM

In [65]:
#Генерация одномерного массива int
# np.random.randint(минимальное значение, максимальное значение, количество)
np.random.randint(1, 10, size = 5)

array([9, 9, 3, 9, 2])

In [70]:
#Генерация матрицы
np.random.randint(1, 10, size = (4,5))

array([[1, 3, 2, 3, 6],
       [7, 1, 1, 9, 3],
       [4, 6, 3, 2, 1],
       [9, 5, 9, 6, 5]])

Step_2.13.12 - На вход подаётся одномерный массив типа np.bool. Функция должна вернуть True если все значения в массиве равны False. Иначе функция должна вернуть False.

In [73]:
#вариант №1
import numpy as np

def solution(m1d):
    result = np.where(any(m1d) == False, True, False )
    return result

In [ ]:
import numpy as np

def solution(m1d):
    result = ~any(m1d)
    return result

Step_2.13.14 - На вход подаётся матрица. Посчитайте сумму элементов верхнего треугольника:
![Картинка испарилась(((](https://ucarecdn.com/934e33ab-ab16-4063-a600-267384dcdd03/)

In [ ]:
import numpy as np

def solution(m2d):
    return np.triu(m2d).sum()

Step_2.13.16 - На вход подаётся одномерный массив. Посчитайте количество уникальных значений.

In [72]:
import numpy as np

def solution(m1d):
    result = len(np.unique(m1d))
    return result