In [1]:
import numpy as np

In [2]:
np.random.randint(0, 10, size= 10)

array([0, 4, 8, 1, 1, 4, 2, 4, 1, 5])

In [ ]:
#Допустим мы хотим получить массив. чтобы гарантировано каждый элементы был создан 1 раз

In [7]:
#Простой массив, который мы хотели бы перемешать
m1 = np.arange(10)
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Данная функция генерирует для нас массив, а затем перемешивает его
np.random.permutation(10)

array([1, 8, 7, 0, 9, 4, 2, 5, 3, 6])

In [9]:
#Что если, нам необходимо перемешать готовый массив
#Данная функция ничего не возвращает, она меняет последовательность эл-ов в исходном массиве
np.random.shuffle(m1)
m1

array([4, 2, 5, 8, 6, 7, 0, 9, 3, 1])

In [10]:
#Сгенерируем массив со значениями типа float()
np.random.randn(10)

array([-0.4006988 ,  0.41916956,  0.37794302,  0.35190651,  0.3795758 ,
        1.0648061 ,  1.33714709,  1.77096803, -0.08398946,  0.55392703])

Пояснения про функцию np.random.randn() неудачные. Раз np.random.randn() генерирует нормально распределённые случайные значения, значит есть ненулевая вероятность получить произвольно большое или произвольно малое число, т.е. любое число на действительной оси. Поэтому предложение "прибавить единицу или прибавить двойку", хотя и сработало в данном случае, на видео, совершенно запросто может не сработать. Поэтому для генерации случайных чисел с плавающей точкой удобнее пользоваться функцией np.random.rand(), которая генерирует равномерно распределённые случайные величины больше либо равные 0, и строго меньшие чем 1

In [11]:
#Для генерация двумерного массива необходимо передать два значения
np.random.randn(3,5)

array([[-0.52406178,  1.22711039,  1.99577702,  0.53423668,  1.39337756],
       [-0.35436891,  0.76666152,  1.81681273, -1.41520767, -0.1460786 ],
       [-0.07812421,  0.02407406,  1.52390221, -0.85958381, -1.18307535]])

#### Сохранение массива, функция np.save()
Для этого нам необходимо передать первому аргументы функции название файла, а второму аргументу - массив

In [12]:
m1 = np.arange(10)
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#Сохраним наш файл
#Формат указывать не будем, по умолчанию он будет ".npy"
np.save('my-array', m1)

In [15]:
#Загрузим наш файл
np.load('my-array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Сохранение нескольких массивов в один файл

In [19]:
m2 = np.random.randint(2,5, size=15)
m2

array([4, 2, 4, 4, 4, 4, 3, 4, 2, 3, 4, 4, 4, 4, 3])

In [26]:
#Данная функция сохраняет массивы с расширением .npz
np.savez('arrays', key1=m1, name2=m2)

In [27]:
#При загрузке получаем абракадабру
m12 = np.load('arrays.npz')
m12

In [28]:
#Чтобы получить массив, нам необходимо обратиться к нему по ключу.
m12['key1']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
m12['name2']

array([4, 2, 4, 4, 4, 4, 3, 4, 2, 3, 4, 4, 4, 4, 3])

#### Функция savez_compressed
Сохранение больших массивов со сжатием. Для экономии дискового пространства.

In [30]:
np.savez_compressed('compressed', key1=m1,key2=m2)

In [32]:
arch = np.load('compressed.npz')

In [33]:
arch['key1']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Вообще функция np.load() очень умная, она видит расширение файла и если оно .npz, то она просто держит ссылку на этот файл. Она не грузит его сразу в память. Т.к. в нем может оказаться огромное количество массивов. Она подружает только необходимый массив, когда мы к нему обращаемся по ключу.