#### Важное замечание, когда мы к массиву или какому либо контейнеру применяем .reshape(). Функция не создает нам новый массив, а трансформирует уже существующий.

In [1]:
import numpy as np
m1 = np.arange(50)

In [5]:
# создадим массив матриц m2
m2 = m1.reshape(5,2,5)
m2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [6]:
#приравняем 1ую матрицу к нулю
m2[0] = 0
m2[0]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
#мы видим, что исходная матрица изменилась!
m1

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Почему так происходит? Почему не происходит копирование? Почему трансформируется исходный контейнер?

Дело в том, что если бы мы сразу создавали новый контейнер, то вырастало бы потребление памяти и все работало бы гораздо медленнее. Разработчики Numpy спроектировали все таким образом, что само по себе просто так ничего никуда не копируется. Это очень важно!

Транспонирование — в линейной алгебре это операция над матрицами в результате которой матрица поворачивается относительно своей главной диагонали. При этом столбцы исходной матрицы становятся строками результирующей.

In [11]:
m_t = np.arange(21).reshape((3,7))
m_t

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [10]:
m_t.T

array([[ 0,  7, 14],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [8]:
m_t.transpose()

array([[ 0,  7, 14],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [12]:
m_t2 = m_t.transpose()
m_t2

array([[ 0,  7, 14],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [13]:
m_t2[0] = 0
m_t2

array([[ 0,  0,  0],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [14]:
#мы видим, что изменение строки в m_t2  привело к изменению столбца m_t
m_t

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 0,  8,  9, 10, 11, 12, 13],
       [ 0, 15, 16, 17, 18, 19, 20]])

transpose, как и reshape так же не копирует!

### Функции Numpy (sqrt, abs, floor, ceil, round)

In [21]:
m1 = np.array([2,4,6,8])

In [22]:
m1 + 1

array([3, 5, 7, 9])

In [23]:
m1 ** 2

array([ 4, 16, 36, 64], dtype=int32)

In [26]:
m2 = m1 ** 2
m2

array([ 4, 16, 36, 64], dtype=int32)

In [27]:
np.sqrt(m2) #Возведение в квадрат

array([2., 4., 6., 8.])

In [29]:
m3 = np.array([-2,4,-6,8])
m3

array([-2,  4, -6,  8])

In [32]:
np.abs(m3) #Получение модуля

array([2, 4, 6, 8])

In [34]:
m4 = np.array([2.1,2.6,2.5,2.9])
m4

array([2.1, 2.6, 2.5, 2.9])

In [35]:
np.round(m4) #Округление по правилам округления, за исключение 2.5. Они округляются вниз.

array([2., 3., 2., 3.])

In [36]:
np.ceil(m4) #Округление до ближайшего целого числа вверх

array([3., 3., 3., 3.])

In [37]:
np.floor(m4) #Округление до ближайшего целого числа вниз

array([2., 2., 2., 2.])

#### np.nan - None из python

In [39]:
m4 = np.array([2.1,2.6,2.5,2.9, np.nan])
m4

array([2.1, 2.6, 2.5, 2.9, nan])

In [40]:
#Допустим мы хотим узнать, сколько в массиве значений
len(m4)

5

In [42]:
#Мы получили 5 значений, но фактически их 4. Для проверки на наличе nan использовать след ф-ю:
np.isnan(m4)

array([False, False, False, False,  True])

In [45]:
#ВАЖНО! Если в данных есть пропуски. и мы используем функции. которые делают что то поэлементно.
#Нам необходимо быть аккуратным. Т.к. Numpy их просто пропустит и не предупредит нас!
np.round(m4)

array([ 2.,  3.,  2.,  3., nan])

#### Дополнительный параметр OUT
У каждой ф-ии, которая работает пожлементно, есть дополнительный параметр OUT.

In [ ]:
m3 = np.array([-2,4,-6,8])
m3

In [48]:
np.abs(m3, out = m3) # == m3 = np.abs(m3)
m3

array([2, 4, 6, 8])

### Бинарные функции
Унарные функции - принимают один аргумент.

Бинарные принимают 2 аргумента. 

В нашем случае мы говорим о массивах.

In [52]:
m1 = np.array([1,2,3,4])

In [53]:
m2 = np.array([0,3,2,6])

In [54]:
#Сравнение двух массивов поэлементно и получие из них максимальных элементов
#Сравнение попарное
np.maximum(m1 , m2)


array([1, 3, 3, 6])

In [55]:
#Аналогичная ф-я minimum
np.minimum(m1 , m2)

array([0, 2, 2, 4])

In [56]:
#Данная ф-я складывает элементы между собой
np.add(m1, m2)

array([ 1,  5,  5, 10])

In [57]:
#допустим у нас массивы имют разное количество эл-ов
m1 = np.array([1,2,3,4,11])
m2 = np.array([0,3,2,6])

In [58]:
#получаем ошибку
np.add(m1, m2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [59]:
#допустим мы имеем nan в массиве
m1 = np.array([1,2,np.nan,4])
m2 = np.array([0,3,2,6])

In [60]:
#Здесь спокойно получаем nan
np.add(m1, m2)

array([ 1.,  5., nan, 10.])

In [61]:
#вычитание
np.subtract(m1,m2)

array([ 1., -1., nan, -2.])

In [65]:
#умножение
np.multiply(m1, m2)

array([ 0.,  6., nan, 24.])

In [73]:
# деление
#inf - это бесконечность, мы попробовали поделить на 0
res = m1 / m2

C:\Users\user\AppData\Local\Temp\ipykernel_13828\221953607.py:2: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(m1, m2)
C:\Users\user\AppData\Local\Temp\ipykernel_13828\221953607.py:4: RuntimeWarning: divide by zero encountered in true_divide
  res = m1 / m2


In [67]:
1 / 0

ZeroDivisionError: division by zero

In [72]:
# проверка на наличие подобных "бесконечностей"
np.isinf(res)

array([ True, False, False, False])

In [74]:
#деление 
np.divide(m1, m2)


C:\Users\user\AppData\Local\Temp\ipykernel_13828\3561950422.py:2: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(m1, m2)


array([       inf, 0.66666667,        nan, 0.66666667])

Step 2.10.9 - На вход подаётся матрица. Выполните ее транспонирование, а затем выполните возведение в квадрат каждого значения.

In [75]:
import numpy as np

def solution(arr):
    arr = arr.T ** 2
    return arr

In [76]:
arr = np.arange(21).reshape((3,7))

In [77]:
solution(arr)

array([[  0,  49, 196],
       [  1,  64, 225],
       [  4,  81, 256],
       [  9, 100, 289],
       [ 16, 121, 324],
       [ 25, 144, 361],
       [ 36, 169, 400]], dtype=int32)

Step 2.10.11 - На вход подаётся матрица. 

Вытяните первую и последнюю строчки. 

Сравните поэлементно две строчки и постройте новый одномерный массив, который будет состоять из минимальных значений. 
Например, если первый элемент первой строки больше чем первый элемент последней строки, то в результат должен пойти первый элемент последней строки. Тоже проделайте с остальными элементами.

In [144]:
import numpy as np

def solution(arr):
    arr1, arr2 = arr[0], arr[-1]
    arr = np.minimum(arr1 , arr2)
    return arr

In [143]:
#Второй вариант
import numpy as np

def solution(arr):
    arr = np.minimum(arr[0], arr[-1])
    return arr

Step 2.10.12 - Прежде чем применять бинарную функцию на двух массивах, вы должны быть уверены, что ваши массивы имеют одинаковую размерность. На вход вашей функции подаётся два контейнера. Проверьте, равны ли размерности. Функция должна вернуть True, если размерности равны и False если нет.
Попробуйте оттолкнуться от свойства shape. Посмотрите какие длины у кортежей и что за значения внутри них.

In [146]:
import numpy as np

def solution(a1, a2):
    result = np.shape(a1) == np.shape(a2)
    return result