#### Важное замечание, когда мы к массиву или какому либо контейнеру применяем .reshape(). Функция не создает нам новый массив, а трансформирует уже существующий.

In [2]:
import numpy as np
m1 = np.arange(50)

In [5]:
# создадим массив матриц m2
m2 = m1.reshape(5,2,5)
m2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [6]:
#приравняем 1ую матрицу к нулю
m2[0] = 0
m2[0]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
#мы видим, что исходная матрица изменилась!
m1

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])