In [3]:
#Копируем элементы одного массива в другой. Для того. чтобы 2ой массив не влиял на первый 
#и можно было работать отдельно функция - .copy()
import numpy as np
m1 = np.arange(10)
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
m2 = m1[3:6].copy()
m2

array([3, 4, 5])

In [7]:
m2 = np.zeros(3)
m2

array([0., 0., 0.])

In [6]:
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Работа индексации с двумерными массивами
#Работает она, аналогично с питоновскими списками

In [10]:
m2d = np.array([[1,2,3],[4,5,6]])
m2d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
m2d.shape

(2, 3)

In [12]:
m2d[1][1]

5

In [13]:
m2d[1, 1] #эквивалентный способ записи

5

In [ ]:
#Трехмерные массивы

In [17]:
m3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
m3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
#Для того. чтобы понять что здесь происходит. пользуемся функцией shape
m3d.shape
#(a,b,c)
#a - показывает количество думерных массивов 
#b - Количество строк в массивах
#c - Количество столбцов (элементов в массивах)

(2, 2, 3)

In [19]:
#вытянем значение 11
m3d[1,1,1]

11

In [23]:
#занулим одну из матриц
m3d[1] = np.zeros(3)
m3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [ ]:
#подготовим двумерную матрицу и поработаем с ней

In [24]:
m2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
m2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [25]:
#получим конкретные массивы (в данном случае они же строки)
m2d[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
m2d[3:]

array([[13, 14, 15, 16],
       [17, 18, 19, 20]])

In [27]:
m2d[4]

array([17, 18, 19, 20])

In [32]:
#теперь получим значения по колонкам (столбацам)
#Возьмем первый столбик
m2d[:,0]
#то есть мы взяли все строки и из каждой строки получили элемент с индексом 0

array([ 1,  5,  9, 13, 17])

In [33]:
#Возьмем третью колонку
m2d[:,2]

array([ 3,  7, 11, 15, 19])

In [37]:
#Возьмем вторую и третью колонку
m2d[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [38]:
#Для закрепления получим 1 и 2 строку, элекметны 0,1
m2d[:2,0:2]

array([[1, 2],
       [5, 6]])

In [49]:
#Для закрепления получим 3 и 4 строку, элеметны 3,4
m2d[3:5,2:5]

array([[15, 16],
       [19, 20]])

In [52]:
#Возьмем центр
m2d[1:4, 1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

### Получение элементов с помощью маски
Когда мы делаем запрос через булевую маску, мы не просто вытягиваем элементы.
При использовании маски автоматически происходит копирование.

In [53]:
m = np.arange(5)
m

array([0, 1, 2, 3, 4])

In [54]:
mask = [True, True, False, False, True]

In [55]:
m2 = m[mask]
m2

array([0, 1, 4])

In [56]:
m2 = np.zeros(3)
m2

array([0., 0., 0.])

In [58]:
m

array([0, 1, 2, 3, 4])

Как мы можем применять маски? Допустим мы хотим получить элементы, которые выше, ниже или равны какому то определенном значению. Для этого создаем массив маску.

In [59]:
z = np.array([234,23,12,3,4,6,1,6,3,56])
z

array([234,  23,  12,   3,   4,   6,   1,   6,   3,  56])

In [60]:
z > 5

array([ True,  True,  True, False, False,  True, False,  True, False,
        True])

In [62]:
m = np.array(z>5)
m

array([ True,  True,  True, False, False,  True, False,  True, False,
        True])

In [63]:
#Обращаемся к нашему массивку по маске и получаем только необходимые элементы.
z[m]

array([234,  23,  12,   6,   6,  56])

In [65]:
#Сделаем это аналогичным образом
z[z > 6]

array([234,  23,  12,  56])

In [66]:
z[z > 2]

array([234,  23,  12,   3,   4,   6,   6,   3,  56])

In [67]:
z[z < 22]

array([12,  3,  4,  6,  1,  6,  3])

В следующем задании у нас есть 5 пользователей. И есть таблица с посещением данных пользователей непример секции по дням недели. всего 7 столбцов (дни недели) и два значения 1 - быд, 0 - не был.
Создадим маску, для посещения пользователем Андрей.
И по ней уже получим значения его посещений.

In [77]:
users = np.array(['Андрей', 'Михаил', 'Ольга', 'Джон', 'Андрей'])

In [86]:
visits = np.array([
    [1,0,1,0,0,1,0],
    [1,0,0,1,0,1,1],
    [1,0,1,0,1,1,1],
    [1,0,0,1,0,1,1],
    [1,0,1,0,1,1,1],
])

In [87]:
mask = users == 'Андрей'

In [88]:
mask

array([ True, False, False, False,  True])

In [89]:
visits[mask]

array([[1, 0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 1, 1]])

In [ ]:
#Step_2.5.13
#На вход подается двумерный массив (матрица):вытяните из матрицы указанную область.
#попозже я обязательно научусь вставлять картинки

In [ ]:
import numpy as np

def solution(arr):
    arr = arr[:2,:2]
    return arr

In [ ]:
#Step_2.5.15
#На вход подается двумерный массив (матрица):вытяните из матрицы указанную область.


In [ ]:
import numpy as np

def solution(arr):
    arr = arr[1:3,3:]
    return arr